### ISSUE TITLE
Missing System ID and Password

### ISSUE THREAD

**Issue by jefriabdullah** [melroselabs/smpp-smsc-simulator#11]
**Describe the bug**
There is no System ID & Password specified. Receive 'bind_transceiver_resp :Invalid System ID' from smpplib client.

**To Reproduce**
1. docker-compose up
2. Test using SMPPLib https://pypi.org/project/smpplib/
3. Leave System ID and Password empty

**Expected behavior**
Bind respond from SMSC

**Additional context**
Perhaps the System ID and password can be set somewhere?

**Comment by ml-markhay** [comment]
An empty system ID and password is invalid. To bind to the simulator, set the system ID and password to any other values supported by SMPP.
