### ISSUE TITLE
simulator closes smpp connection after sm_submit

### ISSUE THREAD

**Issue by cubagabriel** [melroselabs/smpp-smsc-simulator#3]
**Describe the bug**
Hello, I tested BIND TRANSCEIVER and ENQUIRE_LINK and both are replied succesfuly, but when I send SUBMIT_SM, simulator closes TCP connection (RST) inmediately.

**To Reproduce**
1. Connection with ESME application

![image](https://user-images.githubusercontent.com/9539220/92194553-968ec000-ee30-11ea-8f57-de391ee17ad2.png)

2. Send SUBMIT_SM to simulator

![image](https://user-images.githubusercontent.com/9539220/92194198-b70a4a80-ee2f-11ea-8569-1c266cffe20a.png)

**Expected behavior**
Simulator should return SUBMIT_SM response with Message ID. Otherwise, if some SMPP field is incorrect, simulator should send some SMPP error instead of closing TCP connection. 

**Packet capture**
Attached is a SUBMIT_SM and TCP RST example:
[submit_error.zip](https://github.com/melroselabs/smpp-smsc-simulator/files/5172410/submit_error.zip)

**Additional context**
Tested with docker on Ubuntu 18 and g++ build on RHEL 7
ESME application succesfully tested with other SMSCs and with Melrose Labs online simulator.

**Comment by ml-markhay** [comment]
Thanks for your detailed report.

Do you see this issue when you bind and immediately send a submit_sm?  The issue might be related to a bind -> enquire_link -> submit_sm sequence of PDUs.

**Comment by cubagabriel** [comment]
Thanks for the reply. 

I deactivated enquire_link on the application and now submit_sm is working, it seems that enquire_link is not following the same sequence IDs as the other PDUs. 
I would expect some kind of SMPP error response in this case. However, as the problem was on ESME, I think the issue can be closed.

**Comment by ml-markhay** [comment]
Thanks for confirming.

This was previously a known problem with the Melrose Labs online SMSC Simulator.  It was fixed in the online service but the code change didn't make it into the GitHub version of the simulator.  Since you've reported the issue we will now update the code in GitHub to resolve this.

Thanks again.

**Comment by ml-markhay** [comment]
Code updated in GitHub to resolve issue.
