### ISSUE TITLE
How test `deliver_sm` to client?

### ISSUE THREAD

**Issue by septs** [melroselabs/smpp-smsc-simulator#5]

**Comment by ml-markhay** [comment]
Generating MO SMS (in a deliver_sm) I only available on the newer SMSC Simulator. See https://melroselabs.com/services/smsc-simulator/.

Delivery receipts in a deliver_sm are supported by the code. Make a submit_sm and specify with the registered_delivery set and a simulated delivery will take place, resulting in a delivery receipt.
